baseurl: /
languageCode: en-US
title: Jakob De La O
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /post/:year/:month/:day/:slug
params:
  about: I love all things related to data and mathematics.
  author: Jakob De La O
  avatar: profile.png
  custom_css: []
  custom_js: []
  occupation: Data Analyst
  social:
    Email: jakobdelao@utexas.edu
    Github: jakob-delao
    LinkedIn: Jakob De La O
    #Twitter: username
menu:
  main:
    - identifier: blog
      name: blog
      url: /post/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300
